DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT,
    FOREIGN KEY (AUTHOR_ID)  REFERENCES AUTHORS (ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID)  REFERENCES GENRES (ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID BIGINT REFERENCES BOOKS (ID) ON DELETE CASCADE,
    TEXT VARCHAR(400),
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);